server:
  port: 8002
spring:
  application:
    name: message-sender
  rabbitmq:
    host: 192.168.99.108
  cloud:
    stream:
      bindings:
        commonOutput:
          destination: streamCommonTopic
          content-type: application/json
        orderOutput:
          destination: streamOrderTopic
          content-type: application/json