spring:
  application:
    name: message
  cloud:
    stream:
      bindings:
        commonInput:
          destination: streamCommonTopic
          group: common
          content-type: application/json
        orderInput:
          destination: streamOrderTopic
          group: order
          content-type: application/json
      rabbit:
        bindings:
          commonInput:
            consumer:
              auto-bind-dlq: true
