spring:
  cloud:
    consul:
      discovery:
        instance-id: sc-order
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
swagger:
  enabled: true
  base-package: cn.net.liaowei.sc.order
  title: "订单服务"
  version: v0.0.1
  host: "{{host}}:8086"