server:
  port: 8086
spring:
  cloud:
    consul:
      host: 192.168.99.1034
      port: 8500
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://192.168.99.108:3306/sc-db?characterEncoding=utf-8&useSSL=false
env:
  dev