server:
  port: 8085
spring:
  cloud:
    consul:
      host: 192.168.99.103
      port: 8500
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://www.liaowei.net.cn:3306/sc-db?characterEncoding=utf-8&useSSL=false