server:
  port: 8085
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://192.168.99.108:3306/sc-db?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.108
env:
  dev