server:
  port: 8085
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://192.168.99.108:3306/sc-db?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.108
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://192.168.99.108:9411
    sender:
      type: web
logging:
  level:
    root: info
    # org.springframework.web: trace
    org.springframework.cloud.openfeign: debug
  graylog:
    host: 192.168.99.108
    port: 12201

env:
  dev